version: '3'

services:
  redisdb:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared-net
  app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_REDIS_HOST: redisdb
    depends_on:
      - redisdb
    networks:
      - shared-net

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/passFile:/mosquitto/config/passFile
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      #- ./mosquitto/log:/mosquitto/log
      - ~/mosquitto/log:/mosquitto/log
    networks:
      - shared-net

  fe:
    build:
      context: ./mqtt-cli-fe/
      dockerfile: Dockerfile
    volumes:
      - './mqtt-cli-fe/:/app'
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_BASE_URL=http://EC2_IP=${EC2_IP:-localhost}:8081
    networks:
      - shared-net
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fe
      - app
    networks:
      - shared-net



networks:
  shared-net:
    driver: bridge




