version: '3'

services:
  redisdb:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared-net
  app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redisdb
    depends_on:
      - redisdb
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge