server:
  port: 8081
spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: 6379
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database

mqqt-config:
  server-uri: tcp://localhost:1883