server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:database

mqqt-config:
  server-uri: tcp://localhost:1883